### ISSUE TITLE
all languages

### ISSUE THREAD

**Issue by priyankaMakwanaP** [amirisback/keyboard#49]
how to add all available languages available in google in setup keyboard languages?

**Comment by amirisback** [comment]
> how to add all available languages available in google in setup keyboard languages?

this look like impossible for me, i never try like this, anyway what language u need?

**Comment by amirisback** [comment]
> and can we select multiple languages and can change from the keyboard?

don't worries i can create that feature, i will do asap

**Comment by priyankaMakwanaP** [comment]
Arabic, hindi, gujarati..

**Comment by priyankaMakwanaP** [comment]
Arabic, hindi, gujarati..

**Comment by priyankaMakwanaP** [comment]
and is it possible to chage numeric one too?

**Comment by amirisback** [comment]
> and is it possible to chage numeric one too?

can u give me sample?

**Comment by amirisback** [comment]
> Arabic, hindi, gujarati..

oke noted i will find that language

**Comment by priyankaMakwanaP** [comment]
> > and is it possible to chage numeric one too?
> 
> can u give me sample?, i still don't get it

okay so in below example, its google's keyboard i have changed language as Arabic so its numeric keyboard is as below ,
![1708323859570](https://github.com/amirisback/keyboard/assets/129162295/2e6bb2f4-997e-42f7-8084-98aa2bd052cb)
![1708323859551](https://github.com/amirisback/keyboard/assets/129162295/0b8b4803-b78d-4cd5-bc2e-0d92e396c4b9)

**Comment by amirisback** [comment]
U cann add some keyboard language in folder 
xml thank you @priyankaMakwanaP
