### ISSUE TITLE
Search View Not Working

### ISSUE THREAD

**Issue by med1n4** [amirisback/keyboard#51]
Hello @amirisback.

I recently cloned down your project and tried to use the search web view only to find that it wasnt working. When I am focused on the Google search bar and type an input, the text doesnt go into the correct search field. The text goes into the original field that opened the keyboard. 

The same thing happens in the Form View too.

I'm wondering if this is a known issue or if there is a fix for this?

Thanks!

**Comment by rafifrabbani** [comment]
after looking at previous version from this library. I manage to found the solution

paste below code to your `KeyboardIME` class
```
override fun onKey(code: Int) {

        val formView = binding?.keyboardForm
        var inputConnection = currentInputConnection

        if (formView?.visibility == View.VISIBLE) {
            val et1 = formView.binding?.etText
            val et1Connection = et1?.onCreateInputConnection(EditorInfo())

            val et2 = formView.binding?.etText2
            val et2Connection = et2?.onCreateInputConnection(EditorInfo())

            val et3 = formView.binding?.etText3
            val et3Connection = et3?.onCreateInputConnection(EditorInfo())

            if (et1?.isFocused == true) {
                inputConnection = et1Connection
            } else if (et2?.isFocused == true) {
                inputConnection = et2Connection
            } else if (et3?.isFocused == true) {
                inputConnection = et3Connection
            }

        } else if (binding?.keyboardWebview?.visibility == View.VISIBLE) {
            inputConnection =
                binding?.keyboardWebview?.binding?.webview?.onCreateInputConnection(EditorInfo())
        } else {
            inputConnection = currentInputConnection
        }
        onKeyExt(code, inputConnection)
    }
```

**Comment by amirisback** [comment]
can u contribute to this project, please fork and make pull request, I would be happy to

**Comment by amirisback** [comment]
> Hello @amirisback.
> 
> I recently cloned down your project and tried to use the search web view only to find that it wasnt working. When I am focused on the Google search bar and type an input, the text doesnt go into the correct search field. The text goes into the original field that opened the keyboard.
> 
> The same thing happens in the Form View too.
> 
> I'm wondering if this is a known issue or if there is a fix for this?
> 
> Thanks!

Thank you for your report, will fix asap
