### ISSUE TITLE
Multiple Theme support

### ISSUE THREAD

**Issue by priyankaMakwanaP** [amirisback/keyboard#63]
Hello, can you add multiple themes for the keyboard, like some other keyboard supports?
below is example:
![image](https://github.com/amirisback/keyboard/assets/129162295/241b0dc5-8c1e-491c-b672-4a689d25f086)

**Comment by amirisback** [comment]
thank you for your request, maybe you can help me for what spesific part u want change for colour

**Comment by priyankaMakwanaP** [comment]
hello thank you for responding this fast 
i want something like this
![image](https://github.com/amirisback/keyboard/assets/129162295/048364de-979a-4f01-b1a6-c3f5ca9d3d54)

**Comment by amirisback** [comment]
wow, this is very challenging, thank you for request, I'll try my best

**Comment by amirisback** [comment]
![Screenshot_2024-02-16-16-56-33-420_com frogobox frogokeyboard dev](https://github.com/amirisback/keyboard/assets/24654871/9aabf7c4-cbab-471e-9077-4579f97e64e8)


it seems like you can get what you want quickly

**Comment by amirisback** [comment]
Check In Progress Here https://github.com/amirisback/keyboard/pull/64

**Comment by amirisback** [comment]
<img width="200px" height="420px" src="https://github.com/amirisback/keyboard/assets/24654871/a39f8f6f-2766-48af-b7e9-cf92bafe20b5">

<img width="200px" height="420px" src="https://github.com/amirisback/keyboard/assets/24654871/38201538-a1f3-4eea-9eda-8eeeff2640b4">

**Comment by amirisback** [comment]
https://github.com/amirisback/keyboard/tree/develop/create-theme-for-keyboard?tab=readme-ov-file#multi-language-support

**Comment by priyanaka08** [comment]
Thank you!
