### ISSUE TITLE
I can't download keyboard

### ISSUE THREAD

**Issue by MXC48** [amirisback/keyboard#69]
Hello, I have a phone without google play service, so I use Aurora store for the play store catalogue and F-droid for FOSS app. But I can't access to the app with aurora, How can I download frogo keyboard ? 
Thanks 🙏

**Comment by amirisback** [comment]
sorry I just got around to replying, you can download it here https://github.com/amirisback/keyboard/releases/tag/1.2.0

![image](https://github.com/user-attachments/assets/c5fca472-7f0e-4e24-863f-5fa944b2d52a)
